"""Yandex oauth

Revision ID: 154e3ebf4251
Revises: 912bc0b24fd0
Create Date: 2022-12-20 21:24:36.428028

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '154e3ebf4251'
down_revision = '912bc0b24fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yandex_id', sa.BigInteger(), nullable=True))
        batch_op.create_unique_constraint(None, ['yandex_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('yandex_id')
    # ### end Alembic commands ###
