"""Change length of string fields

Revision ID: 671e5005c502
Revises: ea07b9cba4d6
Create Date: 2022-12-24 14:08:13.703928

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '671e5005c502'
down_revision = 'ea07b9cba4d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_history', schema=None) as batch_op:
        batch_op.alter_column('device', type_=sa.String(255))

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('name', type_=sa.String(128))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name', type_=sa.String(64))
        batch_op.alter_column('client_service_id', type_=sa.String(64))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('login', type_=sa.String(64))
        batch_op.alter_column('password', type_=sa.String(128))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_history', schema=None) as batch_op:
        batch_op.alter_column('device', type_=sa.String)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('name', type_=sa.String)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name', type_=sa.String)
        batch_op.alter_column('client_service_id', type_=sa.String)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('login', type_=sa.String)
        batch_op.alter_column('password', type_=sa.String)
    # ### end Alembic commands ###
