"""Add oauth table to keep oauth provider's data for user

Revision ID: ea07b9cba4d6
Revises: dfecaac7197a
Create Date: 2022-12-23 19:33:31.217434

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea07b9cba4d6'
down_revision = 'dfecaac7197a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'oauth',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            'provider',
            sa.Enum('yandex', 'github', name='oauthproviders'),
            nullable=True,
        ),
        sa.Column('remote_id', sa.String(length=128), nullable=True),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('remote_id', 'provider', name='remoteid_provider'),
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_yandex_id_key', type_='unique')
        batch_op.drop_column('yandex_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('yandex_id', sa.BIGINT(), autoincrement=False, nullable=True)
        )
        batch_op.execute('DROP TYPE oauthproviders CASCADE')
        batch_op.create_unique_constraint('users_yandex_id_key', ['yandex_id'])
    op.drop_table('oauth')
    # ### end Alembic commands ###
